language: bash

cache:
  directories:
    - cache

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck

before_install:
  # Install a more recent version of docker (19.03 at least)
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Install buildx from our container
  - docker run --name installbuildx dubodubonduponey/utils /dist/buildx version
  - mkdir -p ~/.docker/cli-plugins
  - docker cp installbuildx:/dist/buildx ~/.docker/cli-plugins/docker-buildx
  - docker rm -f installbuildx
  # Enable multi-arch building
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

install:
  - curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.16.0/hadolint-$(uname -s)-$(uname -m)"
    && chmod 700 ./hadolint

script:
  - PATH=$PATH:$(pwd) ./test.sh

matrix:
  include:
    - os: linux
      dist: bionic
      env:
        - DEBOOTSTRAP_SUITE=buster
        - DEBOOTSTRAP_DATE=2020-08-01
        - TEST_DOES_NOT_BUILD=
